version: "3"

services:
  db:
    restart: always
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_DB: ep_db
      POSTGRES_USER: ep_admin
      POSTGRES_PASSWORD: ep_password
      PGDATA: "priv/data/pgdata"
    volumes:
      - ./priv/db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  erl_planner:
    container_name: erl_planner_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"